# Generated by Django 4.0.5 on 2022-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Out for shopping', 'Out for shopping')], default='Pending', max_length=150),
        ),
    ]
