# Generated by Django 4.0.5 on 2022-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_status_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
