# Generated by Django 4.0.5 on 2022-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
