# Generated by Django 3.2.15 on 2022-11-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipping', 'Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
