# Generated by Django 3.2.15 on 2022-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Shipping', 'Shipping')], default='Pending', max_length=150),
        ),
    ]
