# Generated by Django 3.2.15 on 2022-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
