# Generated by Django 3.2.15 on 2022-11-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
    ]
