# Generated by Django 3.2.15 on 2022-11-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Shipping', 'Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
