# Generated by Django 4.0.5 on 2022-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Shipping', 'Shipping')], default='Pending', max_length=150),
        ),
    ]
