# Generated by Django 4.1.5 on 2023-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipping', 'Shipping')], default='Pending', max_length=150),
        ),
    ]
