# Generated by Django 4.1.5 on 2023-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
